SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 200

ASTEROID_SIZE_SMALL = ASTEROID_MIN_RADIUS
ASTEROID_SIZE_SMALL = ASTEROID_MIN_RADIUS * 2
ASTEROID_SIZE_SMALL = ASTEROID_MIN_RADIUS * 3

SCORE_ASTEROID_SMALL = 100
SCORE_ASTEROID_MEDIUM = 50
SCORE_ASTEROID_LARGE = 20

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3



